resolver: lts-13.0

packages:
- .
- ../polysemy-zoo

extra-deps:
  - polysemy-0.5.1.0
  - polysemy-plugin-0.2.1.0
  - first-class-families-0.5.0.0
  - th-abstraction-0.3.1.0
  - unagi-chan-0.4.1.0
  - webdriver-0.9.0.1
  - aeson-1.4.3.0


